# Generated by Django 2.0.1 on 2018-11-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseratelist', '0002_auto_20181128_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル'),
        ),
        migrations.AlterField(
            model_name='music',
            name='total_bells',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='総ベル数'),
        ),
        migrations.AlterField(
            model_name='music',
            name='total_notes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='総ノーツ数'),
        ),
    ]
